--------------------------------------------------------
--  Arquivo criado - Segunda-feira-Maio-25-2015   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence SQ_ID_ACCOUNT
--------------------------------------------------------

   CREATE SEQUENCE  "SQ_ID_ACCOUNT"  MINVALUE 4 MAXVALUE 90000000 INCREMENT BY 1 START WITH 4 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SQ_ID_AGENCY
--------------------------------------------------------

   CREATE SEQUENCE  "SQ_ID_AGENCY"  MINVALUE 3 MAXVALUE 90000000 INCREMENT BY 1 START WITH 3 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SQ_ID_CLIENT
--------------------------------------------------------

   CREATE SEQUENCE  "SQ_ID_CLIENT"  MINVALUE 4 MAXVALUE 90000000 INCREMENT BY 1 START WITH 4 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SQ_ID_SLIP
--------------------------------------------------------

   CREATE SEQUENCE  "SQ_ID_SLIP"  MINVALUE 3 MAXVALUE 90000000 INCREMENT BY 1 START WITH 3 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SQ_ID_TRANSACTION
--------------------------------------------------------

   CREATE SEQUENCE  "SQ_ID_TRANSACTION"  MINVALUE 1 MAXVALUE 90000000 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table ACCOUNTS
--------------------------------------------------------

  CREATE TABLE "ACCOUNTS" 
   (	"ACCOUNT_ID" NUMBER(*,0), 
	"NUMBER_ACCOUNT" VARCHAR2(20 BYTE), 
	"PASSWORD_ACCOUNT" VARCHAR2(50 BYTE), 
	"TYPE_ACCOUNT" NUMBER(*,0), 
	"DATE_OF_CREATION" DATE, 
	"BALANCE" NUMBER(18,2), 
	"CLIENT_ID" NUMBER(*,0), 
	"AGENCY_ID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table AGENCIES
--------------------------------------------------------

  CREATE TABLE "AGENCIES" 
   (	"AGENCY_ID" NUMBER(*,0), 
	"NUMBER_AGENCY" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CLIENTS
--------------------------------------------------------

  CREATE TABLE "CLIENTS" 
   (	"CLIENT_ID" NUMBER(*,0), 
	"NAME" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table SLIPS
--------------------------------------------------------

  CREATE TABLE "SLIPS" 
   (	"SLIP_ID" NUMBER(*,0), 
	"TO_ACCOUNT" NUMBER(*,0), 
	"FROM_ACCOUNT" NUMBER(*,0), 
	"BAR_CODE" VARCHAR2(100 BYTE), 
	"DATE_OF_PAYMENT" DATE, 
	"AMOUNT" NUMBER(18,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TRANSACTIONS
--------------------------------------------------------

  CREATE TABLE "TRANSACTIONS" 
   (	"TRANSACTION_ID" NUMBER(*,0), 
	"ACCOUNT_ID_CREDIT" NUMBER(*,0), 
	"ACCOUNT_ID_DEBIT" NUMBER(*,0), 
	"DATE_TRANSACTION" DATE, 
	"AMOUNT" NUMBER(18,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into ACCOUNTS
SET DEFINE OFF;
Insert into ACCOUNTS (ACCOUNT_ID,NUMBER_ACCOUNT,PASSWORD_ACCOUNT,TYPE_ACCOUNT,DATE_OF_CREATION,BALANCE,CLIENT_ID,AGENCY_ID) values ('1','123-3','202cb962ac59075b964b07152d234b70','1',to_date('25/05/15','DD/MM/RR'),'1000','1','1');
Insert into ACCOUNTS (ACCOUNT_ID,NUMBER_ACCOUNT,PASSWORD_ACCOUNT,TYPE_ACCOUNT,DATE_OF_CREATION,BALANCE,CLIENT_ID,AGENCY_ID) values ('2','456-6','202cb962ac59075b964b07152d234b70','1',to_date('25/05/15','DD/MM/RR'),'1500','2','2');
Insert into ACCOUNTS (ACCOUNT_ID,NUMBER_ACCOUNT,PASSWORD_ACCOUNT,TYPE_ACCOUNT,DATE_OF_CREATION,BALANCE,CLIENT_ID,AGENCY_ID) values ('3','789-9','202cb962ac59075b964b07152d234b70','1',to_date('25/05/15','DD/MM/RR'),'10000','3','2');
REM INSERTING into AGENCIES
SET DEFINE OFF;
Insert into AGENCIES (AGENCY_ID,NUMBER_AGENCY) values ('1','0123-x');
Insert into AGENCIES (AGENCY_ID,NUMBER_AGENCY) values ('2','0456-x');
REM INSERTING into CLIENTS
SET DEFINE OFF;
Insert into CLIENTS (CLIENT_ID,NAME) values ('1','João da Silva');
Insert into CLIENTS (CLIENT_ID,NAME) values ('2','Maria Antonieta');
Insert into CLIENTS (CLIENT_ID,NAME) values ('3','Nutella Corporation');
REM INSERTING into SLIPS
SET DEFINE OFF;
Insert into SLIPS (SLIP_ID,TO_ACCOUNT,FROM_ACCOUNT,BAR_CODE,DATE_OF_PAYMENT,AMOUNT) values ('1','3',null,'1111',to_date('10/06/15','DD/MM/RR'),'150');
Insert into SLIPS (SLIP_ID,TO_ACCOUNT,FROM_ACCOUNT,BAR_CODE,DATE_OF_PAYMENT,AMOUNT) values ('2','3',null,'2222',to_date('10/06/15','DD/MM/RR'),'200');
REM INSERTING into TRANSACTIONS
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index PK_ACCOUNT_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_ACCOUNT_ID" ON "ACCOUNTS" ("ACCOUNT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_AGENCY_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_AGENCY_ID" ON "AGENCIES" ("AGENCY_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_CLIENT_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_CLIENT_ID" ON "CLIENTS" ("CLIENT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_SLIP_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_SLIP_ID" ON "SLIPS" ("SLIP_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_TRANSACTION_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_TRANSACTION_ID" ON "TRANSACTIONS" ("TRANSACTION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index UK_NUMBER_AGENCY
--------------------------------------------------------

  CREATE UNIQUE INDEX "UK_NUMBER_AGENCY" ON "AGENCIES" ("NUMBER_AGENCY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index UQ_ACCOUNT_NUMBER_ACCOUNT
--------------------------------------------------------

  CREATE UNIQUE INDEX "UQ_ACCOUNT_NUMBER_ACCOUNT" ON "ACCOUNTS" ("NUMBER_ACCOUNT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index UQ_SLIPE_BAR_CODE
--------------------------------------------------------

  CREATE UNIQUE INDEX "UQ_SLIPE_BAR_CODE" ON "SLIPS" ("BAR_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table ACCOUNTS
--------------------------------------------------------

  ALTER TABLE "ACCOUNTS" ADD CONSTRAINT "UQ_ACCOUNT_NUMBER_ACCOUNT" UNIQUE ("NUMBER_ACCOUNT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ACCOUNTS" ADD CONSTRAINT "PK_ACCOUNT_ID" PRIMARY KEY ("ACCOUNT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ACCOUNTS" MODIFY ("AGENCY_ID" NOT NULL ENABLE);
  ALTER TABLE "ACCOUNTS" MODIFY ("CLIENT_ID" NOT NULL ENABLE);
  ALTER TABLE "ACCOUNTS" MODIFY ("BALANCE" NOT NULL ENABLE);
  ALTER TABLE "ACCOUNTS" MODIFY ("DATE_OF_CREATION" NOT NULL ENABLE);
  ALTER TABLE "ACCOUNTS" MODIFY ("TYPE_ACCOUNT" NOT NULL ENABLE);
  ALTER TABLE "ACCOUNTS" MODIFY ("PASSWORD_ACCOUNT" NOT NULL ENABLE);
  ALTER TABLE "ACCOUNTS" MODIFY ("NUMBER_ACCOUNT" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table AGENCIES
--------------------------------------------------------

  ALTER TABLE "AGENCIES" ADD CONSTRAINT "UK_NUMBER_AGENCY" UNIQUE ("NUMBER_AGENCY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "AGENCIES" ADD CONSTRAINT "PK_AGENCY_ID" PRIMARY KEY ("AGENCY_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "AGENCIES" MODIFY ("NUMBER_AGENCY" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CLIENTS
--------------------------------------------------------

  ALTER TABLE "CLIENTS" ADD CONSTRAINT "PK_CLIENT_ID" PRIMARY KEY ("CLIENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CLIENTS" MODIFY ("NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SLIPS
--------------------------------------------------------

  ALTER TABLE "SLIPS" ADD CONSTRAINT "UQ_SLIPE_BAR_CODE" UNIQUE ("BAR_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SLIPS" ADD CONSTRAINT "PK_SLIP_ID" PRIMARY KEY ("SLIP_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SLIPS" MODIFY ("BAR_CODE" NOT NULL ENABLE);
  ALTER TABLE "SLIPS" MODIFY ("TO_ACCOUNT" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TRANSACTIONS
--------------------------------------------------------

  ALTER TABLE "TRANSACTIONS" ADD CONSTRAINT "PK_TRANSACTION_ID" PRIMARY KEY ("TRANSACTION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TRANSACTIONS" MODIFY ("AMOUNT" NOT NULL ENABLE);
  ALTER TABLE "TRANSACTIONS" MODIFY ("DATE_TRANSACTION" NOT NULL ENABLE);
  ALTER TABLE "TRANSACTIONS" MODIFY ("ACCOUNT_ID_DEBIT" NOT NULL ENABLE);
  ALTER TABLE "TRANSACTIONS" MODIFY ("ACCOUNT_ID_CREDIT" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table ACCOUNTS
--------------------------------------------------------

  ALTER TABLE "ACCOUNTS" ADD CONSTRAINT "FK_ACCOUNT_AGENCIES" FOREIGN KEY ("AGENCY_ID")
	  REFERENCES "AGENCIES" ("AGENCY_ID") ENABLE;
  ALTER TABLE "ACCOUNTS" ADD CONSTRAINT "FK_ACCOUNT_CLIENTS" FOREIGN KEY ("CLIENT_ID")
	  REFERENCES "CLIENTS" ("CLIENT_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SLIPS
--------------------------------------------------------

  ALTER TABLE "SLIPS" ADD CONSTRAINT "FK_FROM_ACCOUNT" FOREIGN KEY ("FROM_ACCOUNT")
	  REFERENCES "ACCOUNTS" ("ACCOUNT_ID") ENABLE;
  ALTER TABLE "SLIPS" ADD CONSTRAINT "FK_TO_ACCOUNT" FOREIGN KEY ("TO_ACCOUNT")
	  REFERENCES "ACCOUNTS" ("ACCOUNT_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TRANSACTIONS
--------------------------------------------------------

  ALTER TABLE "TRANSACTIONS" ADD CONSTRAINT "FK_TRANSACTION_ACCOUNT_CREDIT" FOREIGN KEY ("ACCOUNT_ID_CREDIT")
	  REFERENCES "ACCOUNTS" ("ACCOUNT_ID") ENABLE;
  ALTER TABLE "TRANSACTIONS" ADD CONSTRAINT "FK_TRANSACTION_ACCOUNT_DEBIT" FOREIGN KEY ("ACCOUNT_ID_DEBIT")
	  REFERENCES "ACCOUNTS" ("ACCOUNT_ID") ENABLE;
--------------------------------------------------------
--  DDL for Trigger AUTO_INCREMENT_ACCOUNT_ID
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "AUTO_INCREMENT_ACCOUNT_ID" 
BEFORE INSERT ON accounts
FOR EACH ROW
BEGIN
  IF :NEW.account_id IS NULL THEN
    :NEW.account_id := SQ_ID_ACCOUNT.nextval;
  END IF;
END;
/
ALTER TRIGGER "AUTO_INCREMENT_ACCOUNT_ID" ENABLE;
--------------------------------------------------------
--  DDL for Trigger AUTO_INCREMENT_AGENCY_ID
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "AUTO_INCREMENT_AGENCY_ID" 
BEFORE INSERT ON agencies
FOR EACH ROW
BEGIN
  IF :NEW.agency_id IS NULL THEN
    :NEW.agency_id := SQ_ID_AGENCY.nextval;
  END IF;
END;
/
ALTER TRIGGER "AUTO_INCREMENT_AGENCY_ID" ENABLE;
--------------------------------------------------------
--  DDL for Trigger AUTO_INCREMENT_CLIENT_ID
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "AUTO_INCREMENT_CLIENT_ID" 
BEFORE INSERT ON clients
FOR EACH ROW
BEGIN
  IF :NEW.client_id IS NULL THEN
    :NEW.client_id := SQ_ID_CLIENT.nextval;
  END IF;
END;
/
ALTER TRIGGER "AUTO_INCREMENT_CLIENT_ID" ENABLE;
--------------------------------------------------------
--  DDL for Trigger AUTO_INCREMENT_SLIP_ID
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "AUTO_INCREMENT_SLIP_ID" 
BEFORE INSERT ON slips
FOR EACH ROW
BEGIN
  IF :NEW.slip_id IS NULL THEN
    :NEW.slip_id := SQ_ID_SLIP.nextval;
  END IF;
END;
/
ALTER TRIGGER "AUTO_INCREMENT_SLIP_ID" ENABLE;
--------------------------------------------------------
--  DDL for Trigger AUTO_INCREMENT_TRANSACTION_ID
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "AUTO_INCREMENT_TRANSACTION_ID" 
BEFORE INSERT ON transactions
FOR EACH ROW
BEGIN
  IF :NEW.transaction_id IS NULL THEN
    :NEW.transaction_id := SQ_ID_TRANSACTION.nextval;
  END IF;
END;
/
ALTER TRIGGER "AUTO_INCREMENT_TRANSACTION_ID" ENABLE;
--------------------------------------------------------
--  DDL for Trigger BALANCE_ACAOUNTS_TRANSACTION
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "BALANCE_ACAOUNTS_TRANSACTION" 
AFTER INSERT ON transactions
FOR EACH ROW
DECLARE
  balance_debit_account accounts.balance%TYPE;
  balance_credit_account accounts.balance%TYPE;
BEGIN
  SELECT balance INTO balance_debit_account FROM accounts WHERE account_id = :NEW.account_id_debit;
  SELECT balance INTO balance_credit_account FROM accounts WHERE account_id = :NEW.account_id_credit;
  
  UPDATE accounts SET balance = (balance_debit_account - :NEW.amount) WHERE account_id = :NEW.account_id_debit;
  UPDATE accounts SET balance = (balance_credit_account + :NEW.amount) WHERE account_id = :NEW.account_id_credit;
END;
/
ALTER TRIGGER "BALANCE_ACAOUNTS_TRANSACTION" ENABLE;
